"""add bot settings fields for setup/publish steps

Revision ID: ac79baccb0bb
Revises: 19b84b14d429
Create Date: 2026-09-18 23:09:22.090390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac79baccb0bb'
down_revision = '19b84b14d429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('forward_to_staff', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('collect_customer_info', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('away_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('widget_domain', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('widget_domain')
        batch_op.drop_column('away_message')
        batch_op.drop_column('collect_customer_info')
        batch_op.drop_column('forward_to_staff')
        batch_op.drop_column('ai_model')

    # ### end Alembic commands ###
